l3af-project/l3afd

.github/workflows/ci-build.yaml
Perform verification of PRs raised to this repo by building the code and running UT.
=> Setup automatic build

kf/bpf.go, kf/kf_unix.go, kf/kf_windows.go
=> Update to sigterm instead of sigkill for Linux

.github/workflows/ci-build-windows.yaml, .github/workflows/ci-build.yaml
Signed-off-by: Satya Pradhan <satyarp@outlook.com>
=> add goimports tool to github actions

kf/bpf.go
=> Fix for artifact download error

kf/nfconfig.go
The CfgVersion check is used for internal usecases. Removing this check now.
=> Remove config version check

apis/configwatch.go, config/config.go, config/l3afd.cfg
Fix for https://github.com/l3af-project/l3af-arch/issues/32
=> Support mTLS to be disabled on non-prod environment

README.md, docs/CONTRIBUTING.md
And fix email URI in contributing file
Signed-off-by: Dave Thaler <dthaler@microsoft.com>
=> Add OpenSSF best practices badge

kf/nfconfig.go
=> Update the check for an empty list

apis/configwatch.go, config/config.go, config/l3afd.cfg
Signed-off-by: a0p0ie5 <a0p0ie5@homeoffice.wal-mart.com>
=> monitoring for tls certificate expiry

apis/configwatch.go, config/config.go
Signed-off-by: a0p0ie5 <atul.prajapati@walmart.com>
In this PR I have changed **CertExpiryWarningDays** to **MTLSCertExpiryWarningDays**
=> Rename a variable 

CODEOWNERS
Creating PR based on todays TSC vote
Signed-off-by: Jason Niesz <Jason.Niesz@walmart.com>
=> remove Satya and add Charles in CODEOWNERS

kf/kf_unix.go
Signed-off-by: sferna1 <santhosh.fernandes@wal-mart.com>
=> Check and mount trace filesystem

.github/workflows/ci-build.yaml
Signed-off-by: sferna1 <santhosh.fernandes@gmail.com>
=> Update artifact upload

docs/prod-deploy-guide.md
Signed-off-by: sferna1 <santhosh.fernandes@gmail.com>
=> Update product deployment guide

.github/workflows/ci-build-windows.yaml
Signed-off-by: Dave Thaler <dthaler@microsoft.com>
=> Use same version of go on windows as on ubuntu in CI/CD

.github/workflows/ci-build.yaml
Signed-off-by: sferna1 <santhosh.fernandes@gmail.com>
=> Update artifact name

README.md
Signed-off-by: Jason Niesz <Jason.Niesz@walmart.com>
=> update README.md doc

Makefile
Signed-off-by: Jason Niesz <Jason.Niesz@walmart.com>
=> Bump version for 1.0.0 release

kf/kf_unix.go, kf/kf_windows.go, kf/nfconfig.go
=> Update BPF map directory creation

kf/kfdebug.go
This PR address #272 . In this PR , I have changed endpoint name.
=> changed endpoint name

kf/kf_unix.go, kf/kfdebug.go
In this I have addressed issue #275 .
=> Updating the ProgID for tc root 

kf/bpf.go, kf/processCheck.go, stats/metrics.go
In this PR I have changed NF references from NF -> BPF for stats
=> changed reference from NF -> BPF for stats

config/config.go
In this PR I changed kernel version minor value .
=> kernel_default-version

README.md
=> added badges in README

signals/signal_unix.go
In this PR I have add other os Signals to support for graceful stop.
[Go signal handling](https://gist.github.com/teocci/acfec49441627bf94cbb0e5228374158#file-handle-os-signals-go-L13)
=> added additional os signals to support for graceful stop

kf/bpf.go
In this PR I have Added Additional Logs.
=> added additional logs

Makefile
Adding -cover flag  to get integration coverage percentage
=> adding cover flag

apis/configwatch.go, apis/handlers/addprog.go, apis/handlers/addprog_test.go, apis/handlers/deleteprog.go, apis/handlers/deleteprog_test.go, apis/handlers/getconfig.go, apis/handlers/getconfig_test.go, apis/handlers/updateconfig.go, apis/handlers/updateconfig_test.go, apis/routes.go, bpfprogs/bpf.go, bpfprogs/bpfCfgs_internal.go, bpfprogs/bpf_test.go, bpfprogs/bpf_test_unix.go, bpfprogs/bpf_test_windows.go, bpfprogs/bpf_unix.go, bpfprogs/bpf_windows.go, bpfprogs/bpfdebug.go, bpfprogs/bpfmap.go, bpfprogs/bpfmap_test.go, bpfprogs/bpfmetrics.go, bpfprogs/bpfmetrics_test.go, bpfprogs/nfconfig.go, bpfprogs/nfconfig_test.go, bpfprogs/processCheck.go, bpfprogs/processCheck_test.go, config.yml, main.go
In this PR I have addressed issue #288
=> Renamed KF --> bpfprogs

bpfprogs/probes.go
This PR enables support for kprobe type  ebpf programs
=> Enable support for kprobe ebpf program

Makefile
Making a seperate tag for cibuild
issue #427 
this PR is dependent on https://github.com/l3af-project/l3af-arch/pull/117
=> fixing make file

CODEOWNERS
Since I haven't been following the repository and am no longer at Microsoft.
=> Remove dthaler from CODEOWNERS file

apis/configwatch.go, bpfprogs/bpf.go, docs/docs.go, docs/swagger.json, docs/swagger.yaml
This PR fixes while stop was missing to execute to stopping of probes and map cleanup and some doc fixes.
=> Update probes into graceful stop

.github/workflows/ci-build.yaml
Added support to upload to docker hub
=> pushing to dockerhub

.github/workflows/ci-build.yaml
=> upload only when branch is main

.github/workflows/ci-build-windows.yaml, .github/workflows/ci-build.yaml, go.mod
=> upgrading go version

docs/graceful-restart-guide.md
=> Update graceful restart user guide

Makefile
Updating version in makefile to latest
=> Updating version in makefile to latest

config/l3afd.cfg
added logfile fields in sample cfg file
=> added logfile fields in sample cfg file

config/l3afd.cfg
=> fixing pid path

bpfprogs/probes.go, bpfprogs/probes_test.go, models/l3afd.go
Implementing support for kretprobes type in eBPF programs
=> Update kretprobe support

bpfprogs/bpf.go, restart/restart.go
path.Join  is giving  incorrect path join; hence updated with better Join path function for urls
=> url_path join updated

bpfprogs/nfconfig.go, stats/metrics.go
added failure metrics when deploy of ebpf_programs failed
=> added failure metrics when deploy of ebpf_programs failed

.github/workflows/ci-build-windows.yaml, .github/workflows/ci-build.yaml
This PR updates go lang version to 1.23
=> Update go build version to 1.23
