kf/nfconfig.go
Currently, the nf config will keep on closing in a loop until the ctx is cancelled. The desired behaviour is to close the function within 900ms else return the Error.
This PR does the same and doesn't keep on closing in a loop for forever.
=> Solved Bug: forever loop for nf close until ctx is cancelled.

.github/workflows/ci-build-windows.yaml, .github/workflows/ci-build.yaml, README.md, kf/bpf.go, kf/bpf_test.go, kf/bpf_test_unix.go, kf/bpf_test_windows.go, kf/kf_unix.go, kf/kf_windows.go, kf/kfmetrics.go, kf/nfconfig.go, kf/processCheck.go, pidfile/pidfile.go
This PR:
* Updates some code from Linux-only calls to cross-platform calls
* For code that I could not find a simple cross-platform call, moved Linux-only code to *_unix.go file and Windows-only code to *_windows.go to create a platform abstraction layer with the same methods implemented (differently) in different files.
* Renamed the LinuxDistribution() function to the more cross-platform-friendly GetPlatform()
* Updated the tests as well
* Added a ci-build-windows.yaml file to the github workflow to test building on windows
* Updated README.md file to fix #11 by documenting what the github workflow does.
This PR does not actually test any actual eBPF functionality, since the ci-build.yaml file didn't either.   That should be done by adding cross-platform tests, since it already runs "go …
=> Initial steps towards getting L3AFD on Windows

CODEOWNERS
He's moving on up! Unfortunately, this means he won't be as involved with L3AF and therefore shouldn't be in CODEOWNERS. Otherwise he unintentionally becomes a blocker for reviews.
=> Remove Karan

CONTRIBUTING.md, README.md, docs/CONTRIBUTING.md
This document is to define steps to contribute. This address the issue #9.
=> Adding contributor's guide

kf/bpf.go
Signed-off-by: Atul-source <atulprajapati6031@gmail.com>
=> Adding winzip artifact support

.github/workflows/ci-build-windows.yaml, .github/workflows/ci-build.yaml, .github/workflows/codeql.yaml, .github/workflows/scorecards-analysis.yml
Fixes #54
Signed-off-by: Dave Thaler <dthaler@microsoft.com>
=> Add OpenSSF scorecard workflow

.github/release.yml
This PR is to make it easier to generate and categorize release notes for l3afd based on labels defined in PRs.
More info on this features is defined below.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
=> add rules for generating release notes

.github/release.yml, pidfile/pidfile.go
If there is no pid that exists we should just log this as info instead of an error as this is normal on start up.
=> Fix pid file logging

kf/bpf.go
Signed-off-by: sanfern <santhosh.fernandes@gmail.com>
=> Update artifact file download

docs/prod-deploy-guide.md
Signed-off-by: sferna1 <santhosh.fernandes@gmail.com>
=> Update l3afd case

kf/bpf.go, kf/processCheck.go, stats/metrics.go
This diff introduces an `interface_name` field to `NFMonitorMap` and renames `network_function` to `ebpf_program`.
Closes #201
=> feat: introduce interface name to NFMonitorMap

kf/bpf.go, kf/kfdebug.go
This diff introduces error handling to the JSON serialization method in `/kf/kfdebug.go`. It also solves #213 by deactivating `*exe.Cmd` in the JSON response (due to which we had the empty response in the first place).
=> feat: introduce error handling to kfdebug

kf/nfconfig.go
This PR updates the issue of not removing ebpf program when invoking delete api from egress chain.
=> update delete ebpf program in tc egress chain

kf/bpf.go, kf/processCheck.go, stats/metrics.go
This diff introduces a new `version` tag to the `l3afd_NFRunning` metric. 
Closes #221
=> feat: introduce version tag to NFRunning metric

.github/workflows/scorecards-analysis.yml
This PR updates scorecard to update id-token permissions. This is needed to access GitHub's OIDC token which verifies the authenticity of the result when publishing it.
=> update scorecard permissions

kf/bpf.go, stats/metrics.go
A new metric is added to track Update failures of eBPF Function. This PR fixes the issue reported in [#282](https://github.com/l3af-project/l3afd/issues/282)
=> L3AFD metric for ebpf program update command failure count

kf/bpf.go
The purpose of this PR is to load the BPF program with the option to reuse maps. When we need to load two programs in case of TM (ingress, egress), shared bpf map i.e. redirect_iface. We need to avoid creating two instance of maps, and pin one map. Here we need to reuse same map for the both programs. 
Implementing this, we need to define maps with the pinning attribute and provide the map pin path during loading from the l3afd. If the map already exists while loading, it will be reuse instead of creating a new one.
=> Update loading bpf programs with reuse map options

kf/bpf.go
Basically when we are loading from only user program (UserProgramDaemon is true)  then we can'nt fetch ProgID . so when 
**IsRunning** function calls the **IsLoaded** it we will fail. In this PR I am fixing that issue.
=> added the case where ProgId can'nt be updated

Makefile
In this PR I added go mod tidy in build  target in make file,and update for version also.
so that ./l3afd --version will show correct version.
=> Makefile fix for build

kf/nfconfig.go
This PR fixes the Issue: https://github.com/l3af-project/l3afd/issues/363
Adding support for deploying EBPF programs for interfaces created after L3AFD started.
=> Adding support for deploying programs for interfaces created on the fly

kf/bpf.go, kf/bpfmap.go, kf/kf_unix.go, kf/kf_windows.go, kf/nfconfig.go
In this PR I have done error handling improvments.
=> improvement in error handling

kf/bpf.go
In this PR addresses #368. In case any bytecode having multiple ebpf programs, are loaded into the kernel. The initial support includes tracepoints only.
=> Enhance existing eBPF programs by incorporating tracepoint support

config/config.go, config/l3afd.cfg, docs/configdoc.md, go.mod, go.sum, main.go
Currently, L3AFD logs are only displayed on STDOUT. However, in some usecases, the logging and metrics framework might require the logs to be saved to persistent storage or discs. This PR add the functionality of allowing user to save logs to the file as well. The file includes log-rotation by default
=> Adding support for saving the logs in a specified file

kf/kf_unix.go
This PR is the fix for the issue https://github.com/l3af-project/l3afd/issues/362
Specifically, in case of Openstack Hypervisors, whenever rate-limit rules are applied (ref: https://wiki.openstack.org/wiki/InstanceResourceQuota#:~:text=quota%3Acpu_period%3D10240000-,Bandwidth,-limits), openstack install HTB and Ingress qdisc. This PR will add support for deploying TC program on the interface with such HTB and Ingress qdisc as well
=> Adding support for loading TC eBPF programs on existing ingress and HTB qdisc

kf/bpf.go, kf/nfconfig.go, kf/nfconfig_test.go
- When an interface is deleted on the fly, and a delete/remove call is received for the that interface, all the programs associated with that interface should be deleted. Hence, in the PR, on receiving a delete call for an unloaded-interface, the local copy of the programs stored in go-interface and the l3af-config-store file is deleted for cleanup
=> Fix for clearing up NF config stored withing the interface and the l3af-config-store file

kf/nfconfig.go, kf/nfconfig_test.go
Internal L3AFD state maintaining the list of interfaces in c.ifaces was getting overwritten in case of update call. These changes especially are relevant when we have NFconfigs for multiple interfaces on the same host. In that case when the NFconfigs for the second interface is added, the c.ifaces variable maintained by L3AFd will be overwritten by the second interface. Instead, these changes add the second and following interface to the map.
=> Add interfaces instead of overwritting in L3AFd

README.md, build-docker/Dockerfile
Changes
---------
- Added Dockerfile to build the Docker image for L3AFD
- Update README with the instructions to build L3AFD Docker image and run it in a Container
Testing
-------
- Able to attach XDP and TC programs using L3AFD Container
=> Running L3AFD in a Docker container

.github/workflows/ci-build.yaml, README.md
Building the Docker image and uploading it to Artifactory as part of CI build.
=> L3AFd Docker build CI integration

.github/workflows/ci-build.yaml, bpfprogs/bpf_test.go, bpfprogs/bpf_test_unix.go
upgraded github actions image to 22.04
=> upgraded github actions image to 22.04

bpfprogs/nfconfig.go
Addressing https://github.com/l3af-project/l3afd/issues/520
In case the payload consist of the configuration which requires eBPF programs for multiple interfaces to be loaded (for example, eth1, eth2, and eth3). 
In the scenario where eth2 exists no more:
- Due to the return statements in the sequential for loop in the current l3afd code will load the eBPF program for eth1, and return directly as eth2 will not be found, without even attempting to load the eBPF program for eth3. 
In this PR, we remove the return statements in the for loop and instead save individual error messages to single variable. This  variable is then returned after the for loop is completed.
=> Fixing incomplete execution of the configuration issue

bpfprogs/bpf.go, bpfprogs/bpf_unix.go
This PR skips pinning the .bss map in hypervisor usecase, and also adds validation to fix out-of-index errors while unloading tc program.
=> Fix bpf program load failure errors 

bpfprogs/nfconfig.go
This PR allows user to skip config store option.
=> Make the l3af-config-store option optional

bpfprogs/bpfmetrics.go, config/config.go
This PR updates the default value for log max backups to 10. It also changes monitor error logs to debug level, which will help reduce multiple log entries in a goroutine.
=> Update log max backup default value

config/config.go, config/l3afd.cfg
This PR changes the default values of metrics-addr, restapi-addr, and ebpf-chain-debug to listen on localhost.
=> Update the endpoints to listen on localhost

bpfprogs/bpf.go, bpfprogs/bpf_unix.go, bpfprogs/bpf_windows.go, bpfprogs/probes.go, bpfprogs/probes_test.go
This PR fixes the Windows build failure occurring with eBPF v0.18.0 or later.
=> Update to support ebpf pkg v0.18.0 or higher
